apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: featureform
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: featureform
    chartVersion: 0.0.0

  # helmVersion identifies the Helm Version used to render the Chart.
  helmVersion: v3
  weight: 1

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: true

  # values are used in the customer environment, as a pre-render step
  # these values will be supplied to helm template
  values:
    global:
      hostname: "repl{{ ConfigOption `hostname`}}"
      embeddedIngress:
        disabled: '{{repl or (ConfigOptionEquals "enable_ingress" "1" | not) IsKurl }}'
        enabled: '{{repl or (ConfigOptionEquals "enable_ingress" "1" | not) (not IsKurl) }}'

  # builder values provide a way to render the chart with all images
  # and manifests. this is used in replicated to create airgap packages
  builder: {}
