{{ if not .Values.global.embeddedIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    allowed-values: CN=client
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "false"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/proxy-body-size: 64ms
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/issuer: letsencrypt-prod
    kots.io/exclude: {{ .Values.global.embeddedIngress.disabled | quote }}
  name: grpc-ingress
spec:
  rules:
    {{ if .Values.global.hostname }}
    - host: {{ .Values.global.hostname }}
    {{ end }}
    - http:
        paths:
          - path: /featureform.serving.metadata.proto.Api/
            pathType: Prefix
            backend:
              service:
                name: featureform-api-server
                port:
                  number: 7878

          - path: /featureform.serving.proto.Feature/
            pathType: Prefix
            backend:
              service:
                name: featureform-api-server
                port:
                  number: 7878


  {{ if .Values.global.tls.enabled }}
  tls:
    - hosts:
        -  {{ .Values.global.hostname }}
      secretName: featureform-ca-secret
  {{ end }}
{{ end }}