apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: featureform-feature-server
  name: featureform-feature-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: featureform
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: featureform
    spec:
      containers:
        - image: "{{ .Values.global.repo | default .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.global.version | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          name: featureform-feature-server
          ports:
            - containerPort: {{ .Values.serving.port }}
            - containerPort: {{ .Values.metrics.port }}
          env:
            - name: SERVING_PORT
              value: 0.0.0.0:{{ .Values.serving.port }}
            - name: METRICS_PORT
              value: 0.0.0.0:{{ .Values.metrics.port }}
            - name: METADATA_HOST
              value: {{ .Values.metadata.host }}
            - name: METADATA_PORT
              value: {{ .Values.metadata.port | quote }}
          resources: {}
status: {}
