apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: featureform-metadata-server
  name: featureform-metadata-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: featureform-metadata-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: featureform-metadata-server
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          name: featureform-metadata-server
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: TYPESENSE_PORT
              value: {{ .Values.typesense.port | quote }}
            - name: TYPESENSE_HOST
              value: {{ .Values.typesense.host }}
            - name: TYPESENSE_APIKEY
              value: {{ .Values.typesense.apikey | quote }}
            - name: ETCD_HOST
              value: {{ .Values.etcd.host  }}
            - name: ETCD_PORT
              value: {{ .Values.etcd.port | quote }}
status: {}
