{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "typesense.fullname" . }}-binding
  labels: {{- include "typesense.labels" . | nindent 4 }}
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ ternary "default" (include "typesense.storageClass" .) (empty (include "typesense.storageClass" .)) }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{ include "typesense.storageClass" . }}
  {{- end }}