apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-prometheus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.hosts.host  }}
      http:
        paths:
          - path: /prometheus
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-prometheus-service
                port:
                  number: 9090
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-dashboard
                port:
                  number: {{ .Values.global.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sandbox-api-server
                port:
                  number: 8000
