name: Linting
on: pull_request

jobs:
  golangci:
    name: Go Linter
    defaults:
      run:
        working-directory: ./
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

        # Dependencies required for when golangci-lint checks imports
      - name: Install grpc_tools
        run: pip install grpcio-tools

      - name: Install Protobuf
        run: sudo snap install protobuf --classic

      - name: Setup Proto
        run: ./gen_grpc.sh

      - name: Gofmt
        run: gofmt -w ./..

      - name: Setup Git Config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Git Commit and Push
        continue-on-error: true
        run: |
          git add .
          git commit -m "gofmt"
          git push

      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.0

      - name: Run Linter
        continue-on-error: true
        run: golangci-lint run ./...
