name: Update Enterprise
on: push

jobs:
  setup:
    name: Run Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hit Webhook
        run: |
          curl -L -X POST   -H "Accept: application/vnd.github+json"   -H "Authorization: Bearer ${{ secrets.ENTERPRISE_TOKEN }}"   -H "X-GitHub-Api-Version: 2022-11-28"    https://api.github.com/repos/featureform/featureform-enterprise/dispatches    -d '{"event_type":"update_upstream","client_payload":{"sha":"${{ github.sha }}"}}'